export const questions = [
"7-Eleven stores were temporarily converted into Kwik E-marts to promote the release of what movie?",
"`Famous for their work on modernist furniture design, Charles and Ray Eames were related how?",
"A 1952 episode of “I Love Lucy was titled “Lucy Is Enceinte” because what English word was censored?",
"A 1960s TV character played by Al Lewis, Count Vladimir Dracula is better known by what name?",
"A 1985 North Atlantic expedition led by Robert Ballard discovered the wreck of what famous ship 73 years after it sank?",
"A 1995 documentary subtitled “Hollywood Madam” examines the rise and fall of what scandalous figure?",
"A 2006 study of phone conversations found that which statement was meant sarcastically 23 percent of the time?",
"A 2008 study in “Reference Services Review” found which of these websites to be about 80% accurate?",
"A 2009 New York Times article coined the term “Ralph Kramden” to refer to what physical trait?",
"A 2010 Billboard hit,”Dog Days are Over” is a song by the British band “Florence and the” what?",
"A 2010 study by dating Web site Badoo.com found which of these nation’s women to be most flirtatious online?",
"A 2010 study found that nearly 70% of what imported item failed to live up to its claims of being “extra virgin”?",
"A 2010 Time magazine article debunks the myth that what group of people are “spoiled,selfish,solitary misfits”?",
"A 2011 box set celebrates the 13-film collaboration between composer Danny Elfman and what film director?",
"A 2011 New York Times obituary for the late Peter Falk discussed the actor’s 30-plus year gig as what TV character?",
"A 20th-century fashion icon, Gabrielle Chanel was better known by what nickname?",
"A bill of fare is more commonly known as a what?",
"A bit in a gossip column that doesn’t mention any names is often called a what?",
"A bit of folk wisdom warns that when you point a finger at someone, how many fingers are pointing back at you?",
"A blacksmith works primarily with what metal?",
"A blanket or shawl made of colored squares sewn or crocheted together is called a what?",
"A book about fashion and gay culture “Don We Now Our Gay Apparel” takes its title from what Christmas carol?",
"A Boston native,what late night host’s sister made her film debut as one of the Eklund sisters in “The Fighter”?",
"A breakthrough in fashion,”jeggings” are leggings designed to look like what?",
"A bushel is a standard unit originally used to measure the weight of what?",
"A caprese salad traditionally includes which of these ingredients?",
"A caramel candy brand since 1903,Werther’s Original is named after a town in the Westphalia region of what country?",
"A cast member of the AMC series “Hell On Wheels,” rapper/actor Lonnie Lynn, Jr. is better known by what stage name?",
"A chemical compound known as DHA is a common active ingredient in what beauty product?",
"A child starting kindergarten in September 2010 will ordinarily graduate from high school in what year?",
"A child starting kindergarten in September of 2010 will ordinarily graduate from high school in what year?",
"A clarsach–a traditional Irish musical instrument–is a kind of what?",
"A classic 1969 work by poet Maya Angelou is titled “I Know Why The Caged Bird” what?",
"A classic 1976 song by Blue Oyster Cult features the advice “Don’t Fear The” what?",
"A classic 1984 Super Bowl commercial titled “1984” introduced what product to the public?",
"A close friend of her Greek actor father,Telly Savalas was the godfather of which of these movie stars?",
"A collection of Sanskrit hymns and verses known as the Vedas are sacred texts in what religion?",
"A college graduate who participates in an ROTC program graduates with a what?",
"A common ailment,dyspepsia gets its name from Greek roots meaning “bad” what?",
"A common ingredient in ice cream and toothpaste, carrageenan is an extract of what?",
"A common Italian expression, “dolce far niente” means “the sweetness of” what?",
"A common palindrome begins “A man,a plan,a canal” and ends with what country’s name?",
"A common pose in yoga,the “plank” position closely resembles which of these routine exercises?",
"A common problem during childhood, nocturnal enuresis is a medical term better known as what?",
"A common site for piercings, the auricle is a cartilaginous region located where on the body?",
"A company known for its atlases and maps was born when William Rand went into business with whom?",
"A contestant on the 2012 season of “Celebrity Apprentice,” Dee Snider won fame as frontman for what 80s band?",
"A contestant on the Fall 2011 season of “Dancing With The Stars,” Carson Kressley first gained fame on what reality show?",
"A couple described as a “Sam and Diane” refers to the on-again,off-again duo of what classic sitcom?",
"A cowcatcher is a metal grill that is commonly found on the front of what type of vehicle?"

]